config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'new_wishlists', to: 'wishlists#new', as: 'new_wishlist'


  resources :games, :users, :wishlists
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :wishlists
    has_many :users, through: :wishlists
end

app/models/user.rb
class User < ApplicationRecord
    has_many :wishlists
    has_many :games, through: :wishlists

    has_secure_password

    validates :user_name, :email_address, :password, presence: true
    validates :password, length: { minimum: 6 }
    validates_uniqueness_of :user_name

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    current_user
    @game = Game.find(params[:id])
    @wishlist = Wishlist.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to games_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to games_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to games_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path
  end

  

  private


  def user_params
    params.require(:user).permit(:user_name, :email_address, :password)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
    def index 
        @wishlists = Wishlist.all
    end
    
    def new
        @wishlist = Wishlist.new
    end

    def create
        @wishlist = Wishlist.create(wishlist_params)

        redirect_to user_path(@wishlist.user_id)
    end

    def edit
        @wishlist = Wishlist.find_by(params[:id])
        @user = User.find_by_id(@wishlist.user_id)
    end

    def destroy
        @wishlist = Wishlist.find_by(params[:id])
        @wishlist.destroy
        redirect_to user_path(@wishlist.user_id)
    end

    private

    def wishlist_params
        params.require(:wishlist).permit(:game_id, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/games/index.html.erb
<br><br>
<ul>
<% @games.each do |game|%>
<li><img src = "<%=game.img_url%>" width="200" height="300"></li>
<li><%= link_to game.title, game_path(game)%></li>
<p>rating :<%= game.rating%></p>
<%end%>
</ul>

app/views/games/show.html.erb
<br><br>
<img src = "<%=@game.img_url%>" width="200" height="300">
<h1><%= @game.title %></h1>

<div class="">
<h4>Desription:</h4>
<p><%= @game.description %></p>

<p><%= "Rating: #{@game.rating} ⭐️, Price: $#{@game.price}" %></p>



<%= form_for @wishlist do |f| %>

<%=f.hidden_field :user_id, value: @current_user.id%>
<%=f.hidden_field :game_id, value: @game.id%>

<%= f.submit "add to Wishlist"%>
<% end %>

<hr>
<%= link_to "home", games_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LevelUpGames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "nav">
    <% if current_user %>
      Logged in as <%=link_to current_user.user_name, user_path(current_user)%>
      <p><%= link_to "Log Out", logout_path %></p>
    <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
    <% end %>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/users/edit.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <%= f.label :user_name %></br>
    <%= f.text_field :user_name %>
    <br>
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
    <br>
    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.submit  %>
<% end %>

<hr>
<%= link_to "home", games_path%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div class="form-input">
    <%= f.label :user_name %></br>
    <%= f.text_field :user_name %>
  </div>
  <div class="form-input">
    <%= f.label :email_address %></br>
    <%= f.text_field :email_address %>
  </div>
  <div class="form-input">
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
<%= link_to "home", games_path%>

app/views/users/show.html.erb
<hr>
<h1> <%= @user.user_name%> page</h1>
<p><%=link_to "edit", edit_user_path%></p>
<hr>
<h3><strong>Wishlist</strong></h3>
<ul>
<%@user.wishlists.each do |wishlist|%>
    <p><%= link_to wishlist.game.title, game_path(wishlist.game_id)%></p>
    <p><img src="<%=wishlist.game.img_url%>" width="200" height="300"></p>
    <p>Price: $<%= wishlist.game.price%></p>
    <p>Rating: <%= wishlist.game.rating%>⭐️</p>
    <%= button_to "Remove from Wishlist", wishlist_path(wishlist), method: :delete %>

    <hr>
<%end%>
</ul>
<hr>
<%= link_to "home", games_path%>

app/views/wishlists/new.html.erb
Add to Wishlist
<%= form_for @wishlist do |f|%>

<%=f.label :game_id%>
<%=f. collection_select :game_id, Game.all, :id, :title%>

<%=f.label :user_id%>
<%=f.collection_select :user_id, User.all, :id, :user_name%>

<%=f.submit%>
<%end%>